version: "2.1"
services:
  redis:
    image: "redis:5.0.5"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    ports:
      - "8083:8083"
      - "8086:8086"

  telegraf:
    container_name: telegraf
    image: telegraf:1.12.3
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=y
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__SCHEDULER__STATSD_ON=True
      - AIRFLOW__SCHEDULER__STATSD_HOST=telegraf
      - AIRFLOW__SCHEDULER__STATSD_PORT=8125
      - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
      - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=5
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - LOAD_EX=y
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__SCHEDULER__STATSD_ON=True
      - AIRFLOW__SCHEDULER__STATSD_HOST=telegraf
      - AIRFLOW__SCHEDULER__STATSD_PORT=8125
      - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
      - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=5
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__SCHEDULER__STATSD_ON=True
      - AIRFLOW__SCHEDULER__STATSD_HOST=telegraf
      - AIRFLOW__SCHEDULER__STATSD_PORT=8125
      - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
      - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=5
    command: worker

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
